main:
  - name: Support
    identifier: support
    weight: 100
    url: https://github.com/hbstack
    params:
      header: The HB support community.
      icon:
        vendor: font-awesome-solid
        name: headset

  - name: Documentation
    parent: support
    url: https://hbstack.dev/
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
        className: text-primary
      description: The HB Stack documentation.