description: The amateur radio station operator KQ4AFY website

hb:
  # js_bundle_name: main # the JS bundle name.
  # css_bundle_name: main # the CSS bundle name.
  header:
    brand: KQ4AFY # the brand name, leave it empty to use site's title.
    # logo_bg: '#712cf9' # logo background color, used by logo with transparent background.
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      github: jbouse
      paypal: KQ4AFY
      tiktok: butonlyone.life
  footer:
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      github: jbouse
      paypal: KQ4AFY
      tiktok: butonlyone.life
  blog:
    paginate: 12 # paginate.
    # post_thumbnail: false # whether to show the thumbnails.
    # post_date_format: ":date_long" # see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts.
    home: # homepage settings.
      featured_posts: 5 # the number of the featured posts.
      main_sections: # leave it empty to include all regular pages.
        - docs
        - blog
        - tutorials
    disqusShortname: kq4afy
  docs:
    disqusShortname: kq4afy
  content_panel:
    repo:
      service: github # github or gitlab.
      repo: ugns/kq4afy-theme
      branch: main
      # subpath: exampleSite
  # gallery:
  #   thumbnail_size: "x640"

seo:
  favicons: # see https://hugomods.com/en/docs/seo/#favicons-module
    icon: images/logo.png # use logo as favicon.
    sizes:
    - size: 16x16
    - size: 32x32
    - size: 150x150
    - rel: apple-touch-icon
      size: 180x180
    - size: 192x192

# PWA settings, see https://hugomods.com/en/docs/pwa/#site-parameters.
pwa:
  debug: false
  manifest:
    background_color: '#712cf9'
    theme_color: '#712cf9'
    short_name: 'HB Theme'

# see https://hugomods.com/en/docs/search/#site-parameters
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  shortcut_search: ["/"]

gravatar:
  default: wavatar
  rating: pg

mermaid:
  # replace it with other CDNs or self-hosted URLs.
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hugopress:
  modules:
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
        head-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
        body-end:
          cacheable: true
